name: Keep Render Backend Alive

on:
  schedule:
    # Run every 10 minutes (adjust as needed)
    # Render free tier spins down after 15 min of inactivity
    - cron: '*/10 * * * *'
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Ping Health Endpoint
        run: |
          echo "🏓 Pinging Mister Donkey backend..."
          
          # Replace with your actual Render URL
          BACKEND_URL="${{ secrets.BACKEND_URL || 'https://your-app.onrender.com' }}"
          
          # Ping health endpoint with timeout
          response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 60 "${BACKEND_URL}/health")
          
          echo "Response code: $response"
          
          if [ "$response" = "200" ]; then
            echo "✅ Backend is alive and responding"
            exit 0
          elif [ "$response" = "000" ]; then
            echo "⏳ Backend is spinning up (cold start)..."
            echo "Waiting 30 seconds and retrying..."
            sleep 30
            
            # Retry once
            response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 60 "${BACKEND_URL}/health")
            if [ "$response" = "200" ]; then
              echo "✅ Backend responded after cold start"
              exit 0
            else
              echo "❌ Backend failed to respond after retry"
              exit 1
            fi
          else
            echo "⚠️ Unexpected response code: $response"
            exit 1
          fi
      
      - name: Log Success
        if: success()
        run: |
          echo "📊 Keep-alive ping successful at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
      
      - name: Log Failure
        if: failure()
        run: |
          echo "🚨 Keep-alive ping failed at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo "Backend may be down or experiencing issues"

# To use this:
# 1. Create .github/workflows/ directory in your repo
# 2. Save this as .github/workflows/keep-alive.yaml
# 3. In GitHub repo settings → Secrets → Actions
#    Add secret: BACKEND_URL = https://your-actual-app.onrender.com
# 4. Commit and push
# 5. Go to Actions tab to see it running